### ISSUE TITLE
Character Token and Character Portrait shown above name

### ISSUE THREAD

**Issue by sinanm89** [ElfFriend-DnD/foundryvtt-5eOGLCharacterSheet#16]

**Comment by akrigline** [comment]
Is there more to this issue that failed to submit? I'm not sure if what you're saying here is a suggestion, bug, or what. The Character Token and Portrait are definitely not _supposed_ to be shown above the name. If they are, I could use details about what setup you have.

If you're suggesting that they be displayed above the name, that's a different matter entirely.

**Comment by akrigline** [comment]
Going to close this as I suspect it is better encapsulated by #18
