### ISSUE TITLE
Bug - Adding Proficiency to Saving Throws Not Possible

### ISSUE THREAD

**Issue by ImSullymon** [ElfFriend-DnD/foundryvtt-5eOGLCharacterSheet#17]
I've uninstalled all modules to ensure nothing conflicts. It is currently impossible using OGL to add Proficiency to Saving Throws. It does work with Skills, just not Saving Throws.

**Comment by akrigline** [comment]
Thanks for the report! I'll take a look at this asap.

**Comment by akrigline** [comment]
fixed in 0.5.5
