### ISSUE TITLE
Enhancement - Add a button to set Character Art for Actor

### ISSUE THREAD

**Issue by ImSullymon** [ElfFriend-DnD/foundryvtt-5eOGLCharacterSheet#18]
Currently, the only way to set character art to appear in the Actor Directory is to switch off of OGL, set it, then switch OGL back on. Suggestion to add a button above/below the name to add the art, strictly to the directory page, not to the sheet itself.

Note: The token art works just fine, just character art is impossible to access currently.

**Comment by akrigline** [comment]
Thanks for the suggestion! I think I might add this to the Biography Tab, above appearance. The area around the character name could work, I'll have to play with that to see how the spacing works out.

**Comment by akrigline** [comment]
done in 0.5.5. Added character image to Bio Tab above Appearance.
