### ISSUE TITLE
Bug - Cannot Click "Initiative" to roll for Initiative

### ISSUE THREAD

**Issue by ImSullymon** [ElfFriend-DnD/foundryvtt-5eOGLCharacterSheet#19]
Currently, you cannot click the word "Initiative" to roll for combat initiative. You have to switch back to the default 5e sheet or enter in a /r 1d20 + dex into chat.

**Comment by ImSullymon** [comment]
I have also disabled all other modules to make sure nothing conflicts.

**Comment by akrigline** [comment]
Dang. I thought I fixed that. Thanks for the report! I'll take a look asap.

**Comment by ImSullymon** [comment]
Thanks!

**Comment by akrigline** [comment]
Fixed in 0.5.6
