### ISSUE TITLE
OGL Sheet still not opening (v. 0.6.2, DND5e 1.20, Foundry 0.7.8)

### ISSUE THREAD

**Issue by knownamerob** [ElfFriend-DnD/foundryvtt-5eOGLCharacterSheet#22]
Opening up the game, I go to preexisting and new tokens, and nothing happens when I double click, but then checking the console, I see this: 

d {description: undefined, fileName: undefined, lineNumber: undefined, endLineNumber: undefined, message: "An error occurred while rendering OGL5eCharacterSheet 103: Missing helper: "ogl5e-isEmpty"", …}
description: undefined
endLineNumber: undefined
fileName: undefined
lineNumber: undefined
message: "An error occurred while rendering OGL5eCharacterSheet 103: Missing helper: "ogl5e-isEmpty""
name: "Error"
number: undefined
  | (anonymous) | @ | foundry.js:4481
-- | -- | -- | --
  | Promise.catch (async) |   |  
  | render | @ | foundry.js:4479
  | render | @ | foundry.js:5626
  | _onClickLeft2 | @ | foundry.js:41941
  | callback | @ | foundry.js:36337
  | _handleClickLeft2 | @ | foundry.js:36539
  | _handleMouseDown | @ | foundry.js:36501
  | a.emit | @ | index.js:181
  | r.dispatchEvent | @ | InteractionManager.ts:1106
  | r.processPointerDown | @ | InteractionManager.ts:1307
  | t.recursiveFindHit | @ | TreeSearch.ts:173
  | t.recursiveFindHit | @ | TreeSearch.ts:113
  | t.recursiveFindHit | @ | TreeSearch.ts:113
  | t.recursiveFindHit | @ | TreeSearch.ts:113
  | t.findHit | @ | TreeSearch.ts:200
  | r.processInteractive | @ | InteractionManager.ts:1177
  | r.onPointerDown | @ | InteractionManager.ts:1252

I checked the Discord for others who were having similar troubles, and I saw you suggest to download and activate Compact Character sheet, so I have that installed and active, and it still wont open any sheet using 5e OGL

**Comment by akrigline** [comment]
I can reproduce, taking another look. I swear I fixed this...

**Comment by akrigline** [comment]
(fixed in 0.6.4)
