### ISSUE TITLE
Feature - Add cheboxes for equip and unequip items on items panel

### ISSUE THREAD

**Issue by p4535992** [ElfFriend-DnD/foundryvtt-5eOGLCharacterSheet#24]
**Environment Details**

Foundry VTT Version: 0.7.9

Operating System: \[Linux\]

How Are You Using Foundry: \[Linux,Native Application (Electron), Chrome\]

Which Game System: Dungeons and Dragons 5th Edition, version 1.2.0

Modules Enabled?: yes

OS, Hosting, Browser (if applicable): Linux/Node/Chrome

Module Version : 0.6.4

**Description Details**

Add a checkbox for equip and unequip items like in the new version of the character sheet by roll 20.

![img](https://i.imgur.com/0gY6FhA.png)

**Comment by akrigline** [comment]
Inventory panel is awful crowded. Moving currency up top would alleviate some of that, which I bet is why Roll20 did it.

**Comment by akrigline** [comment]
Coming in 0.9.0
