### ISSUE TITLE
Compatibility Risk Flag

### ISSUE THREAD

**Issue by AsianDumpring** [ElfFriend-DnD/foundryvtt-5eOGLCharacterSheet#26]
Currently on Foundry 0.7.9, D&D 5e Game System Version 1.2.4 and I'm getting a compatibility risk flag

**Comment by akrigline** [comment]
You can ignore those flags for the most part. Unless something has been shown to have broken, I don't tend to push up an update just to fix this little number. I maybe should but I've got other stuff to do...

There's a sea of compatibility risk flags in module territory, all it means is the number hasn't been incremented.
