### ISSUE TITLE
Bug - Restore Inventory Icons functionality

### ISSUE THREAD

**Issue by bcartwright** [ElfFriend-DnD/foundryvtt-5eOGLCharacterSheet#27]
Sometime between version 0.6.4 and 0.7.3 , the Add Icons to Inventory option stopped adding icons to most items outside of the actions box. 

Screenshots from versions 0.6.4 and 0.7.3 , with no non-required modules installed.
0.6.4
![OGL-064-default](https://user-images.githubusercontent.com/16912450/109195019-e484e080-774e-11eb-9bf1-049339d93e8b.png)
0.7.3
![OGL-073-default](https://user-images.githubusercontent.com/16912450/109194052-e4381580-774d-11eb-950a-a2b530f126c5.png)

If this was an intended change, could we get an additional option to have **_maximum icons_**?
Otherwise, I hope to see inventory icons return in future versions.

**Comment by bcartwright** [comment]
I learned something else: 
With 0.6.4, the character sheets only have **_maximum icons_** when viewed in the foundry browser. Opening the same sheets, same setup, in e.g. google chrome, it's missing icons in the same way as 0.7.3 .

I'm not sure whether this would be the same fix, but it would be great to have **_maximum icons_** in chrome or some other browser as well.

**Comment by akrigline** [comment]
Thanks for the detailed report @bcartwright that's super helpful. This must have slipped through the cracks, I wouldn't be surprised if there is a CSS change in core which we weren't expecting. I'll take a look and see if I can get a fix out.

**Comment by akrigline** [comment]
Fixed in v0.8.0! Was some code that i overambitiously deleted after the transition to Actions List module integration.
