### ISSUE TITLE
Items with charges/uses do not display charge/use count.

### ISSUE THREAD

**Issue by aestrada4355** [ElfFriend-DnD/foundryvtt-5eOGLCharacterSheet#28]
Features and Spells with limited charges/uses display the current value/max value, however, Equipment does not.

![image](https://user-images.githubusercontent.com/67869538/111016548-97bf1d80-837c-11eb-8c8d-77e2f369472e.png)
![image](https://user-images.githubusercontent.com/67869538/111016613-f5536a00-837c-11eb-9573-b26e03b0e160.png)

**Comment by akrigline** [comment]
Coming in 0.9.0
