### ISSUE TITLE
No uses being displayed in Equipment  for magic items with charges

### ISSUE THREAD

**Issue by wwitunsky** [ElfFriend-DnD/foundryvtt-5eOGLCharacterSheet#29]
I have created a magic item with charges and it does not show the remaining charges in the inventory view. Only way to see the remaining charges is to goto the edit screen. I can see charges for features but not items.
![image](https://user-images.githubusercontent.com/33044255/111016676-419eaa00-837d-11eb-8f7c-0067a984cb5d.png)

**Comment by akrigline** [comment]
Duplicate of #28 (but thanks for the report!)
