### ISSUE TITLE
Uncaught (in promise) TypeError: abl is undefined

### ISSUE THREAD

**Issue by Umgak** [ElfFriend-DnD/foundryvtt-5eOGLCharacterSheet#34]
DnD5e version: 1.5.3
Foundry version: 0.8.9
D&D 5e OGL Character Sheet version: 0.13.0

Due to a recent change in the 5e system, the code on [this line](https://github.com/ElfFriend-DnD/foundryvtt-5eOGLCharacterSheet/blob/7d9dd558f2be6866ecde7d7ffc94d40bb8a01be5/src/foundryvtt-5eOGLCharacterSheet.ts#L83) now sets ability to undefined, causing a TypeError in rollAbilitySave as the abilityId is not a valid value. I managed to work around this with the following (warning! ugly) code:
`let ability = event.currentTarget.textContent.substring(0,3).toLowerCase();`
I know for a fact that I'm doing that in the worst and most disgusting way possible (especially as it's language-dependent), but it's at least functional for me until this module gets updated by someone who actually knows JS. I certainly don't.
Thanks!

**Comment by akrigline** [comment]
I believe I fixed this in 0.14.1
Thanks for all the details you provided! It was really helpful.
