### ISSUE TITLE
[Suggestion] Make saving throws clickable like skills are

### ISSUE THREAD

**Issue by SLinxTheFox** [ElfFriend-DnD/foundryvtt-5eOGLCharacterSheet#35]
Just to be able to click on the text here for a quick saving throw just like you can for skills

https://i.imgur.com/HGhgeSX.png

**Comment by SLinxTheFox** [comment]
it now responds to clicking, but it rolls "Undefined Save" that's a +2 for some reason. character has neither a +2 mod nor +2 proficiency
https://i.imgur.com/8uUgVVP.png

**Comment by akrigline** [comment]
closing in favor of #37
