### ISSUE TITLE
[Bug] Clickable saving throws return back "undefined save" always with a +2 bonus

### ISSUE THREAD

**Issue by SLinxTheFox** [ElfFriend-DnD/foundryvtt-5eOGLCharacterSheet#37]
When i click on a saving throw via the saving throws section (not via the ability scores) what the title says happens

https://i.imgur.com/ygHgOX7.png

I get this error in the console when it happens 
`foundry.js:5120 game.data.version is deprecated since V9 in favor of game.version`

**Comment by akrigline** [comment]
I believe I fixed this in 0.14.1
Thanks for all the details you provided! It was really helpful.
